# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automatic build and deploy of the application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
permissions:
  contents: write

jobs:
  build-and-deploy:

    name: make build and deploy to gh-pages branch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm clean-install
    - run: npm run build  # npm run deploy would build and deploy but it's better to split these two
    - name: copy
      env:
        SRC_FOLDER_PATH: 'static'
        TARGET_BRANCH: 'gh-pages'
      run: |
        files=$(find $SRC_FOLDER_PATH -type f) # get the file list
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch                         # fetch branches
        git checkout $TARGET_BRANCH       # checkout to your branch
        git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
        git add -A
        git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
        git push origin $TARGET_BRANCH # push to remote branch
